export const MOCK_EVENTS = [
  {
    id: 1,
    title: 'AI Summit 2027',
    description: 'Join top AI researchers, founders, and engineers discussing the future of LLMs, robotics, and artificial general intelligence.',
    category: 'Technology',
    city: 'Bangalore',
    venue: 'KTPO Exhibition Centre, Whitefield',
    eventDate: '2027-02-14',
    time: '09:30 AM',
    price: 1499,
    seats: 500,
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=800&q=80',
    featured: true,
    organizerName: 'TechNext India',
  },
  {
    id: 2,
    title: 'Sunburn Festival Goa',
    description: 'Asia’s largest electronic dance music festival featuring world-class DJs, immersive lights, and beachside celebration.',
    category: 'Music',
    city: 'Goa',
    venue: 'Vagator Beach Grounds',
    eventDate: '2026-12-28',
    time: '04:00 PM',
    price: 2999,
    seats: 3000,
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=800&q=80',
    featured: true,
    organizerName: 'Sunburn Media',
  },
  {
    id: 3,
    title: 'Startup Founders Mixer',
    description: 'Exclusive networking event for startup founders, angel investors, and venture capitalists in South India.',
    category: 'Business',
    city: 'Bangalore',
    venue: 'The Oberoi, MG Road',
    eventDate: '2026-09-12',
    time: '06:00 PM',
    price: 799,
    seats: 150,
    rating: 4.7,
    imageUrl: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=800&q=80',
    featured: true,
    organizerName: 'Founders Club',
  },
  {
    id: 4,
    title: 'Indie Music Night',
    description: 'An acoustic evening featuring India’s finest independent singer-songwriters under the open sky.',
    category: 'Music',
    city: 'Mumbai',
    venue: 'NCPA Open Air Theatre',
    eventDate: '2026-08-22',
    time: '07:00 PM',
    price: 499,
    seats: 350,
    rating: 4.6,
    imageUrl: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?auto=format&fit=crop&w=800&q=80',
    featured: true,
    organizerName: 'Acoustics Live',
  },
  {
    id: 5,
    title: 'Comedy Carnival',
    description: 'Back-to-back standup comedy sets by top national comedians. Guaranteed non-stop laughs!',
    category: 'Comedy',
    city: 'Hyderabad',
    venue: 'Shilpakalam Vedika',
    eventDate: '2026-08-30',
    time: '06:30 PM',
    price: 699,
    seats: 600,
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=800&q=80',
    featured: true,
    organizerName: 'Laugh Out Loud Club',
  },
  {
    id: 6,
    title: 'Modern Art Exhibition',
    description: 'A curated showcase of contemporary paintings, sculptures, and digital art installations by emerging artists.',
    category: 'Art & Culture',
    city: 'Delhi',
    venue: 'National Gallery of Modern Art',
    eventDate: '2026-10-05',
    time: '11:00 AM',
    price: 299,
    seats: 400,
    rating: 4.5,
    imageUrl: 'https://images.unsplash.com/photo-1536924940846-227afb31e2a5?auto=format&fit=crop&w=800&q=80',
    featured: true,
    organizerName: 'Delhi Art Foundation',
  },
  {
    id: 7,
    title: 'Mindful Wellness Retreat',
    description: 'Rejuvenate your body and mind with guided meditation, sound therapy, and holistic wellness workshops.',
    category: 'Wellness',
    city: 'Mysuru',
    venue: 'Lalitha Mahal Palace Gardens',
    eventDate: '2026-09-20',
    time: '07:00 AM',
    price: 1199,
    seats: 100,
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?auto=format&fit=crop&w=800&q=80',
    featured: true,
    organizerName: 'Prana Wellness',
  },
  {
    id: 8,
    title: 'Culinary Masterclass',
    description: 'Hands-on gourmet cooking masterclass with celebrity chefs, featuring fusion Asian and Mediterranean dishes.',
    category: 'Food & Drink',
    city: 'Bangalore',
    venue: 'The Culinary Academy, Indiranagar',
    eventDate: '2026-08-10',
    time: '02:00 PM',
    price: 1899,
    seats: 40,
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=800&q=80',
    featured: true,
    organizerName: 'Gourmet Guild',
  },
  {
    id: 9,
    title: 'Marathon for a Cause',
    description: 'Annual charity 10K & 21K run promoting environmental sustainability and green city initiatives.',
    category: 'Sports',
    city: 'Bangalore',
    venue: 'Kanteerava Stadium',
    eventDate: '2026-11-02',
    time: '05:30 AM',
    price: 499,
    seats: 2000,
    rating: 4.7,
    imageUrl: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=800&q=80',
    featured: true,
    organizerName: 'RunForGreen India',
  },
];

export const MOCK_TESTIMONIALS = [
  { id: 1, name: 'Karthik Iyer', city: 'Hyderabad', rating: 5, quote: 'Seat selection, instant e-tickets, clean refunds when a show got rescheduled - genuinely premium experience.' },
  { id: 2, name: 'Rohit Mehta', city: 'Mumbai', rating: 5, quote: 'Eventora’s founder mixers are how I met my co-founder. The platform just gets the details right.' },
  { id: 3, name: 'Ananya Rao', city: 'Bangalore', rating: 5, quote: 'Flawless UI, super fast checkout, and love the instant QR ticket delivery!' },
];

export const MOCK_STATS = {
  totalEvents: 9,
  ticketsSold: 4850,
  activeUsers: 1250,
  cityCount: 6,
};
